---
- name: config creation
  gather_facts: false
  hosts: localhost
  vars_files:
    - leaf101_var.yml

  tasks:
    - name: generate leaf config
      template: 
        src=configuration_template.j2
        dest={{ hostname }}.cfg
      delegate_to: localhost