---
switches:

  - switch:
      hostname: leaf101
      lb0_ip: 10.0.0.101
      lb0_mask: 255.255.255.255
      mgmt_ip: 192.168.100.101
      mgmt_mask: 255.255.255.0
      uplinks:
        - uplink_port: Ten1/0/1
          uplink_ip: 192.168.0.1
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine1
          uplink_spine_port: Ten1/0/1
        - uplink_port: Ten1/0/2
          uplink_ip: 192.168.0.3
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine2
          uplink_spine_port: Ten1/0/1
        - uplink_port: Ten1/0/3
          uplink_ip: 192.168.0.5
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine3
          uplink_spine_port: Ten1/0/1
        - uplink_port: Ten1/0/4
          uplink_ip: 192.168.0.7
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine4
          uplink_spine_port: Ten1/0/1
      vlans:
        - vlan_number: 2101
          vlan_name: Mainframe
          vlan_ip: 10.100.100.1
          vlan_mask: 255.255.255.0
        - vlan_number: 2102
          vlan_name: X86_Servers
          vlan_ip: 10.100.110.1
          vlan_mask: 255.255.255.0
      routing:
        - ospf_instance: 1
          core_ospf_area: 0.0.0.0
          stub_ospf_area: 0.1.0.1
      snmp:
        - asset_tag: DEADBEEF
          location: Bunker
          contact: me@here.com, 555.555.1212
      ntp_servers:
        - 10.104.10.10
        - 10.134.10.10
      syslog_servers:
        - 10.100.101.36
        - 10.150.101.36
        - 100.100.100.100

  - switch:
      hostname: Leaf102
      lb0_ip: 10.0.0.102
      lb0_mask: 255.255.255.255
      mgmt_ip: 192.168.100.102
      mgmt_mask: 255.255.255.0
      uplinks:
        - uplink_port: Ten1/0/1
          uplink_ip: 192.168.0.9
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine1
          uplink_spine_port: Ten1/0/2
        - uplink_port: Ten1/0/2
          uplink_ip: 192.168.0.11
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine2
          uplink_spine_port: Ten1/0/2
        - uplink_port: Ten1/0/3
          uplink_ip: 192.168.0.13
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine3
          uplink_spine_port: Ten1/0/2
        - uplink_port: Ten1/0/4
          uplink_ip: 192.168.0.15
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine4
          uplink_spine_port: Ten1/0/2
      vlans:
        - vlan_number: 2101
          vlan_name: Mainframe
          vlan_ip: 10.100.100.1
          vlan_mask: 255.255.255.0
        - vlan_number: 2102
          vlan_name: X86_Servers
          vlan_ip: 10.100.110.1
          vlan_mask: 255.255.255.0
      routing:
        - ospf_instance: 1
          core_ospf_area: 0.0.0.0
          stub_ospf_area: 0.1.0.1
      snmp:
        - asset_tag: ABAB1234
          location: Bunker
          contact: me@here.com, 555.555.1212
      ntp_servers:
        - 10.104.10.10
        - 10.134.10.10
      syslog_servers:
        - 10.100.101.36
        - 10.150.101.36
        - 100.100.100.100

  - switch:
      hostname: Leaf103
      lb0_ip: 10.0.0.103
      lb0_mask: 255.255.255.255
      mgmt_ip: 192.168.100.103
      mgmt_mask: 255.255.255.0
      uplinks:
        - uplink_port: Ten1/0/1
          uplink_ip: 192.168.0.17
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine1
          uplink_spine_port: Ten1/0/3
        - uplink_port: Ten1/0/2
          uplink_ip: 192.168.0.19
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine2
          uplink_spine_port: Ten1/0/3
        - uplink_port: Ten1/0/3
          uplink_ip: 192.168.0.21
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine3
          uplink_spine_port: Ten1/0/3
        - uplink_port: Ten1/0/4
          uplink_ip: 192.168.0.23
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine4
          uplink_spine_port: Ten1/0/3
      vlans:
        - vlan_number: 2101
          vlan_name: Mainframe
          vlan_ip: 10.100.100.1
          vlan_mask: 255.255.255.0
        - vlan_number: 2102
          vlan_name: X86_Servers
          vlan_ip: 10.100.110.1
          vlan_mask: 255.255.255.0
      routing:
        - ospf_instance: 1
          core_ospf_area: 0.0.0.0
          stub_ospf_area: 0.1.0.1
      snmp:
        - asset_tag: AFAF4444
          location: Bunker
          contact: me@here.com, 555.555.1212
      ntp_servers:
        - 10.104.10.10
        - 10.134.10.10
      syslog_servers:
        - 10.100.101.36
        - 10.150.101.36
        - 100.100.100.100

  - switch:
      hostname: Leaf104
      lb0_ip: 10.0.0.104
      lb0_mask: 255.255.255.255
      mgmt_ip: 192.168.100.104
      mgmt_mask: 255.255.255.0
      uplinks:
        - uplink_port: Ten1/0/1
          uplink_ip: 192.168.0.25
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine1
          uplink_spine_port: Ten1/0/4
        - uplink_port: Ten1/0/2
          uplink_ip: 192.168.0.27
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine2
          uplink_spine_port: Ten1/0/4
        - uplink_port: Ten1/0/3
          uplink_ip: 192.168.0.29
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine3
          uplink_spine_port: Ten1/0/4
        - uplink_port: Ten1/0/4
          uplink_ip: 192.168.0.31
          uplink_mask: 255.255.255.254
          uplink_spine_switch: Spine4
          uplink_spine_port: Ten1/0/4
      vlans:
        - vlan_number: 2101
          vlan_name: Mainframe
          vlan_ip: 10.100.100.1
          vlan_mask: 255.255.255.0
        - vlan_number: 2102
          vlan_name: X86_Servers
          vlan_ip: 10.100.110.1
          vlan_mask: 255.255.255.0
      routing:
        - ospf_instance: 1
          core_ospf_area: 0.0.0.0
          stub_ospf_area: 0.1.0.1
      snmp:
        - asset_tag: ABAB3099
          location: Bunker
          contact: me@here.com, 555.555.1212
      ntp_servers:
        - 10.104.10.10
        - 10.134.10.10
      syslog_servers:
        - 10.100.101.36
        - 10.150.101.36
        - 100.100.100.100