---
- name: config creation
  gather_facts: false
  hosts: localhost
  vars_files:
    - config_variables.yml

  tasks:
    - name: generate leaf config
      template: 
        src=config_template.j2
        dest={{ hostname }}.cfg
      delegate_to: localhost